### ISSUE TITLE
Fix crash when adding duplicate book

### ISSUE THREAD

**Issue by alicia-mctc** [alicia-mctc/readinglist#1]
Program crashes when two books with the same author and title are added

To reproduce

Select option 1 to add a book. Enter book information
Select option 1 to add another book. Enter the same book information as before

Program crashes with the following stack trace

Traceback (most recent call last):
  File "main.py", line 74, in <module>
    main()
  File "main.py", line 16, in main
    action()
  File "main.py", line 36, in add_book
    new_book.save()
  File ".../python/readinglist/bookstore.py", line 24, in save
    self.bookstore._add_book(self)
  File ".../python/readinglist/bookstore.py", line 85, in _add_book
    raise BookError(f'This book is already in the store. {book}')
bookstore.BookError: This book is already in the store. ID None, Title: E, Author: E. You have not read this book.

Suggest adding try-except block in main.py to catch the exception, and print a useful message to the user.

**Comment by Davidbillingsley** [comment]
@alicia-mctc  Would you like some help with the issues you have?  I am learning python and copied your code to practice.  I managed to fix most of your _issues_ .   I worked on _issues_ 1 4 5 7 8.  During my testing the code works correctly.  I also modified the code a bit to be a little more PEP8 compliant.

**Comment by alicia-mctc** [comment]
Sure.  That will be helpful.  Could you be available before meeting time this morning?
________________________________

**Comment by Davidbillingsley** [comment]
I am sorry, I don't have time till monday afternoon.  If you want we can talk via email.  I will be able to respond via emails periodically over the next few days.
