### ISSUE TITLE
Add description of program to README.md

### ISSUE THREAD

**Issue by alicia-mctc** [alicia-mctc/readinglist#6]
Add a short description of the program and it's features to README.md
@ajsmash7 ajsmash7 mentioned this issue on Jan 31, 2019
Added Description of Program #9
Closed
claraj pushed a commit that referenced this issue on Feb 3, 2019
@qaalib101
Merge pull request #7 from qp3580ug/class_docs
2adf2

**Comment by jy8474np** [comment]
Issue resolved. Program description added to README.md
